name: C/C++ CI

on:
  push:
    branches: [ "*" ]  # Trigger on push to all branches
  pull_request:
    branches: [ "*" ]  # Trigger on pull requests to all branches

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install cmake

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      run: |
        cd build
        make

    - name: Run tests
      run: |
        cd build
        make test  # This will run your simple tests
